@echo off
set PLAYWRIGHT_MOCK_MODE=1
set RUN_ON_START=1
set RUN_ON_START_DELAY_MS=800
set AUTONOMOUS_WORKER_INTERVAL_SECONDS=0
set ENFORCE_LINKEDIN_SESSION=0
set DISABLE_MONGO=1
set DISABLE_REDIS=1
set LOG_LEVEL=INFO
"%~dp0dist\TitanScraper.exe"
